### ISSUE TITLE
Login/ Registeration backend

### ISSUE THREAD

**Issue by LordArjuna** [ILUVUS/iluvus-backend-api-JIA-3317#2]
We will receive the data from the frontend regarding the user details

- We will have one common endpoint that receives all HTTP requests from the front end.
- We will use the data received from this call to do the following 

1. We will look for the user in the Users database table for users using the register page(success or failure message)
2. We will verify the email ID(professional?) of a new user. We will either send back a failure message or add new info to the table and send back a success message

**Comment by LordArjuna** [comment]
https://chat.openai.com/share/1493e57a-3942-4880-bb32-cbd50ca03560    This is critical to understanding our setup. 
https://medium.com/@singhandresh09/using-protobuf-in-react-native-7cc8286389f5
https://protobuf.dev/

**Comment by thuanvoit** [comment]
https://blog.logrocket.com/using-axios-with-react-native-manage-api-requests/
